name = "faultloc"
description = "A description of the experiment"
store = "/Users/akeles/.etna/store.json"

[[workloads]]
name = "RBT"
language = "Rust"

[[workloads]]
name = "STLC"
language = "Rust"
