#!/usr/bin/env bash
# Fork & push one Python workload to alpaylan/<dir>-etna, mirroring the
# Rust convention (origin=fork, upstream=real, .hegel/.log/progress ignored).
#
# Idempotent — safe to re-run. If the fork already exists, gh skips
# create. If remotes are already wired correctly, git skips re-add.
#
# Usage: scripts/fork_python_workload.sh <workload-dir-name>
#   e.g. scripts/fork_python_workload.sh sortedcontainers

set -euo pipefail

D=${1:?usage: $0 <workload-dir-name>}
ROOT=/Users/akeles/Programming/projects/PbtBenchmark/faultloc/workloads/Python/$D
[ -d "$ROOT" ] || { echo "no such workload: $ROOT" >&2; exit 2; }

cd "$ROOT"
echo "=== $D ==="

# 1. Reset marauders to base in case a prior variant left source modified.
marauders reset >/dev/null 2>&1 || true

# 2. Drop the spurious root /uv.lock (etna's setup_steps used to run
#    `uv sync` here before we wrapped it; the lockfile we care about is
#    etna/uv.lock).
rm -f uv.lock

# 3. Append our gitignore entries idempotently. Match the Rust convention
#    (/.hegel, /etna.log, /progress.jsonl) plus Python extras.
mkdir -p .  # noop, just guarantees cwd
touch .gitignore
add_ignore() {
  local line=$1
  grep -qxF "$line" .gitignore || echo "$line" >> .gitignore
}
add_ignore "/.hegel"
add_ignore "/etna.log"
add_ignore "/progress.jsonl"
add_ignore "/.marauders"
add_ignore "/uv.lock"
add_ignore "/etna/.venv"
add_ignore "/etna/etna.log"
add_ignore "/etna/.hypothesis"
add_ignore "__pycache__/"
add_ignore "*.egg-info/"
add_ignore ".pytest_cache/"

# scaffold_python_workload.py originally added "etna/uv.lock" to .gitignore.
# That was wrong — the lockfile pins hypothesis-crosshair versions and SHOULD
# be committed for reproducibility. Strip it if present.
if grep -qx "etna/uv.lock" .gitignore; then
  python3 -c '
import sys
from pathlib import Path
p = Path(".gitignore")
lines = p.read_text().splitlines()
p.write_text("\n".join(l for l in lines if l.strip() != "etna/uv.lock") + "\n")
'
fi

# 4. Stage everything that should land in the commit. `git add -A` picks
#    up modified, deleted, and new — exactly what we want post-reset.
git add -A

# 5. Commit if there's anything staged.
if git diff --cached --quiet; then
  echo "  (nothing staged — already committed?)"
else
  git commit -m "etna: scaffold $D workload (Hypothesis + CrossHair backends)" \
             -m "Generated by etna-ify (etna-ify/prompts/run-python.md). Adds:" \
             -m "  - etna.toml, BUGS.md, TASKS.md, steps.json — manifest + etna driver config" \
             -m "  - patches/*.patch — patch-kind variants (forward-apply injects bug)" \
             -m "  - etna/etna_runner/ — runner package: properties, strategies, witnesses, runner" \
             -m "  - etna/pyproject.toml + etna/uv.lock — locked Hypothesis & hypothesis-crosshair deps" \
             -m "Run: etna experiment run --tests $D" \
             -m "Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"
fi

# 6. Create the fork on GitHub if it doesn't exist.
FORK="alpaylan/${D}-etna"
if ! gh repo view "$FORK" >/dev/null 2>&1; then
  upstream_origin=$(git remote get-url origin)
  echo "  creating $FORK"
  gh repo create "$FORK" \
    --public \
    --description "ETNA workload fork of $upstream_origin (Hypothesis + CrossHair)" \
    --disable-issues \
    --disable-wiki >/dev/null
else
  echo "  fork $FORK already exists"
fi

# 7. Rewire remotes: origin → fork, upstream → original origin.
if ! git remote get-url upstream >/dev/null 2>&1; then
  upstream_url=$(git remote get-url origin)
  git remote add upstream "$upstream_url"
  echo "  upstream = $upstream_url"
fi
fork_url="git@github.com:${FORK}.git"
if [ "$(git remote get-url origin 2>/dev/null)" != "$fork_url" ]; then
  git remote set-url origin "$fork_url"
  echo "  origin = $fork_url"
fi

# 8. Push.
branch=$(git rev-parse --abbrev-ref HEAD)
git push -u origin "$branch"
echo "  pushed $branch -> $FORK"
