#!/usr/bin/env bash
# Fork & push one Haskell workload to alpaylan/<dir>-etna, mirroring
# the Python convention (origin=fork, upstream=real).
#
# Idempotent — safe to re-run.
#
# Usage: scripts/fork_haskell_workload.sh <workload-dir-name>
#   e.g. scripts/fork_haskell_workload.sh pretty-simple

set -euo pipefail

D=${1:?usage: $0 <workload-dir-name>}
ROOT=/Users/akeles/Programming/projects/PbtBenchmark/faultloc/workloads/Haskell/$D
[ -d "$ROOT" ] || { echo "no such workload: $ROOT" >&2; exit 2; }

cd "$ROOT"
echo "=== $D ==="

# 1. Append our gitignore entries idempotently.
touch .gitignore
add_ignore() {
  local line=$1
  grep -qxF "$line" .gitignore || echo "$line" >> .gitignore
}
add_ignore "/.hegel/"
add_ignore "/.marauders/"
add_ignore "/etna.log"
add_ignore "/progress.jsonl"
add_ignore "/dist-newstyle/"
add_ignore "/etna/dist-newstyle/"

# 2. Stage everything (modified + new).
git add -A

# 3. Commit if there's anything staged.
if git diff --cached --quiet; then
  echo "  (nothing staged — already committed?)"
else
  git commit -m "etna: scaffold $D workload (QuickCheck + Hedgehog + Falsify + SmallCheck)" \
             -m "Generated by etna-ify (etna-ify/prompts/run-haskell.md). Adds:" \
             -m "  - etna.toml, BUGS.md, TASKS.md, steps.json — manifest + etna driver config" \
             -m "  - patches/*.patch — patch-kind variants (forward-apply injects bug)" \
             -m "  - etna/ — runner package: Properties, per-framework Gens, Witnesses, Main" \
             -m "  - cabal.project — extended to include etna/ alongside upstream" \
             -m "Run: etna experiment run --tests $D" \
             -m "Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"
fi

# 4. Create the fork on GitHub if it doesn't exist.
FORK="alpaylan/${D}-etna"
if ! gh repo view "$FORK" >/dev/null 2>&1; then
  upstream_origin=$(git remote get-url origin)
  echo "  creating $FORK"
  gh repo create "$FORK" \
    --public \
    --description "ETNA workload fork of $upstream_origin (QuickCheck + Hedgehog + Falsify + SmallCheck)" \
    --disable-issues \
    --disable-wiki >/dev/null
else
  echo "  fork $FORK already exists"
fi

# 5. Rewire remotes: origin → fork, upstream → original origin.
if ! git remote get-url upstream >/dev/null 2>&1; then
  upstream_url=$(git remote get-url origin)
  git remote add upstream "$upstream_url"
  echo "  upstream = $upstream_url"
fi
fork_url="git@github.com:${FORK}.git"
if [ "$(git remote get-url origin 2>/dev/null)" != "$fork_url" ]; then
  git remote set-url origin "$fork_url"
  echo "  origin = $fork_url"
fi

# 6. Push.
branch=$(git rev-parse --abbrev-ref HEAD)
git push -u origin "$branch"
echo "  pushed $branch -> $FORK"
